import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { AuthProvider } from "@/context/AuthContext";
import SubNavbar from "@/components/SubNavbar/SubNavbar";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TuTiendaApple",
  description: "Generated by create next app",
  };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        
        <AuthProvider>
          <Toaster position="top-center" toastOptions={{duration: 3000, style: {background: '#333', color: '#fff' }}}/>
              <Navbar/>
              <SubNavbar/>      
                {children}       
              <Footer/>              
        </AuthProvider>
        
      </body>
    </html>
  );
}
